export const badges = [
  {
    id: 'streak-3',
    name: 'Tris',
    description: '3 giorni consecutivi senza fumare',
    icon: '🥉',
    checker: (stats) => stats.streakDays >= 3,
  },
  {
    id: 'streak-7',
    name: 'Maratoneta',
    description: '7 giorni consecutivi senza fumare',
    icon: '🏃',
    checker: (stats) => stats.streakDays >= 7,
  },
  {
    id: 'streak-14',
    name: 'Iron Man',
    description: '14 giorni consecutivi senza fumare',
    icon: '🦾',
    checker: (stats) => stats.streakDays >= 14,
  },
  {
    id: 'streak-30',
    name: 'Eroe',
    description: '30 giorni consecutivi senza fumare',
    icon: '🦸',
    checker: (stats) => stats.streakDays >= 30,
  },
  {
    id: 'avoided-100',
    name: 'Risparmiatore',
    description: '100 sigarette evitate',
    icon: '💰',
    checker: (stats) => stats.avoidedTotal >= 100,
  },
  {
    id: 'avoided-500',
    name: 'Cassaforte',
    description: '500 sigarette evitate',
    icon: '🏦',
    checker: (stats) => stats.avoidedTotal >= 500,
  },
  {
    id: 'avoided-1000',
    name: 'Tesoro',
    description: '1000 sigarette evitate',
    icon: '💎',
    checker: (stats) => stats.avoidedTotal >= 1000,
  },
  {
    id: 'level-5',
    name: 'Apprendista',
    description: 'Raggiungi il livello 5',
    icon: '🎓',
    checker: (stats) => stats.level >= 5,
  },
  {
    id: 'level-10',
    name: 'Maestro',
    description: 'Raggiungi il livello 10',
    icon: '🧙',
    checker: (stats) => stats.level >= 10,
  },
  {
    id: 'level-20',
    name: 'Leggenda',
    description: 'Raggiungi il livello 20',
    icon: '🏆',
    checker: (stats) => stats.level >= 20,
  },
];
